version: '3'

services:
  nginx:
    container_name: test_task_nginx
    image: nginx:stable-alpine
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html
     # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      #- /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - test-task-network

  php-fpm:
    container_name: test_task_php_fpm
    build:
      context: ./docker/php-fpm
    working_dir: /var/www/html
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    networks:
      - test-task-network

  mysql:
    container_name: test_task_mysql
    image: mysql
    ports:
        - "3307:3306"
    volumes:
      - ./docker/logs/mysql:/var/log/mysql
      - ./docker/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime/:ro
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
    restart: always
    networks:
      - test-task-network

  phpmyadmin:
     container_name: test_task_phpmyadmin
     image: phpmyadmin/phpmyadmin
     platform: linux/amd64
     links:
         - mysql
     environment:
         PMA_HOST: mysql
         PMA_PORT: 3306
         PMA_ARBITRARY: 1
         UPLOAD_LIMIT: 300M
     restart: always
     ports:
         - 8081:80
     networks:
       - test-task-network

networks:
  test-task-network:
